export const awsAliasMap = {
    "ELB": ["Elastic Load Balancer", "Load Balancer", "Classic Load Balancer", "ELB"],
    "ALB": ["Application Load Balancer", "ALB"],
    "NLB": ["Network Load Balancer", "NLB"],
    "EC2": ["Elastic Compute Cloud", "EC2"],
    "S3": ["Simple Storage Service", "S3"],
    "RDS": ["Relational Database Service", "RDS"],
    "Aurora": ["Amazon Aurora", "Aurora"],
    "DynamoDB": ["Amazon DynamoDB", "DynamoDB"],
    "Lambda": ["AWS Lambda", "Lambda"],
    "IAM": ["Identity and Access Management", "IAM"],
    "VPC": ["Virtual Private Cloud", "VPC"],
    "ECS": ["Elastic Container Service", "ECS"],
    "EKS": ["Elastic Kubernetes Service", "EKS"],
    "EBS": ["Elastic Block Store", "EBS"],
    "EFS": ["Elastic File System", "EFS"],
    "SQS": ["Simple Queue Service", "SQS"],
    "SNS": ["Simple Notification Service", "SNS"],
    "SES": ["Simple Email Service", "SES"],
    "CloudFront": ["Amazon CloudFront", "CloudFront"],
    "Route53": ["Amazon Route 53", "Route 53", "Route53"],
    "CloudWatch": ["Amazon CloudWatch", "CloudWatch"],
    "CloudTrail": ["AWS CloudTrail", "CloudTrail"],
    "WAF": ["Web Application Firewall", "WAF"],
    "ASG": ["Auto Scaling Group", "Auto Scaling", "ASG"],
    "KMS": ["Key Management Service", "KMS"],
    "SageMaker": ["Amazon SageMaker", "SageMaker"],
    "Lex": ["Amazon Lex", "Lex"],
    "Polly": ["Amazon Polly", "Polly"],
    "Textract": ["Amazon Textract", "Textract"],
    "Comprehend": ["Amazon Comprehend", "Comprehend"],
    "Transcribe": ["Amazon Transcribe", "Transcribe"],
    "Rekognition": ["Amazon Rekognition", "Rekognition"],
    "Bedrock": ["Amazon Bedrock", "Bedrock"],
    "Q": ["Amazon Q", "Q"],
    "Amplify": ["AWS Amplify", "Amplify"],
    "Cloud9": ["AWS Cloud9", "Cloud9"],
    "CloudShell": ["AWS CloudShell", "CloudShell"],
    "Cognito": ["Amazon Cognito", "Cognito"],
    "Athena": ["Amazon Athena", "Athena"],
    "Redshift": ["Amazon Redshift", "Redshift"],
    "QuickSight": ["Amazon QuickSight", "QuickSight"],
    "Glue": ["AWS Glue", "Glue"],
    "Fargate": ["AWS Fargate", "Fargate"],
    "AppSync": ["AWS AppSync", "AppSync"],
    "StepFunctions": ["AWS Step Functions", "Step Functions"],
    "CodeBuild": ["AWS CodeBuild", "CodeBuild"],
    "CodeDeploy": ["AWS CodeDeploy", "CodeDeploy"],
    "CodePipeline": ["AWS CodePipeline", "CodePipeline"],
    "Inspector": ["Amazon Inspector", "Inspector"],
    "GuardDuty": ["Amazon GuardDuty", "GuardDuty"],
    "Macie": ["Amazon Macie", "Macie"],
    "SecurityHub": ["AWS Security Hub", "Security Hub"],
    "ResilienceHub": ["AWS Resilience Hub", "Resilience Hub"],
    "Outposts": ["AWS Outposts", "Outposts"],
    "LocalZones": ["AWS Local Zones", "Local Zones"],
    "WorkSpaces": ["Amazon WorkSpaces", "WorkSpaces"],
    "Lightsail": ["Amazon Lightsail", "Lightsail"],
    "AppFlow": ["Amazon AppFlow", "AppFlow"],
    "Snowball": ["AWS Snowball", "Snowball"],
    "Snowcone": ["AWS Snowcone", "Snowcone"],
    "DataSync": ["AWS DataSync", "DataSync"],
    "ControlTower": ["AWS Control Tower", "Control Tower"],
    "TrustedAdvisor": ["AWS Trusted Advisor", "Trusted Advisor"],
    "Organizations": ["AWS Organizations", "Organizations"],
    "Budgets": ["AWS Budgets", "Budgets"],
    "CostExplorer": ["AWS Cost Explorer", "Cost Explorer"],
    "WellArchitected": ["AWS Well-Architected Tool", "Well Architected", "Well-Architected"]
};