export const EVENT_TYPE = {
    FROM_PAGE: "FROM_PAGE",
    FROM_EXTENSION: "FROM_EXTENSION",
}

export const EVENT_ACTION = {
    GPT_STREAM_PART: "GPT_STREAM_PART",
    GPT_STREAM_DONE: "GPT_STREAM_DONE",
    EXT_LOST_CONNECTION: "EXT_LOST_CONNECTION",
    EXT_CHECK: "EXT_CHECK",
    EXT_PRESENT: "EXT_PRESENT",
    SEND_PROMPT: "SEND_PROMPT",
}
